IEE.Web/Areas/ttn_content/Models/TestViewModel.cs
using IEE.Infrastructure.DbContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IEE.Web.Areas.ttn_content.Models
{
    public class TestViewModel
    {
        public SATTest Test { get; set; }
        public List<SATUserAnswer> ListAnswer { get; set; }
        public int Section { get; set; }
        public int Content { get; set; }
        public string TypeName { get; set; }
        public TestViewModel()
        {

        }
        public TestViewModel(SATTest model)
        {
            Test = model;
        }
    }
}

IEE.Web/Controllers/SATTestController.cs
using IEE.Infrastructure.DbContext;
using IEE.Web.Areas.ttn_content.Models;
using IEE.Web.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IEE.Web.Controllers
{
    [Authorize(Roles = "Examinee")]

    public class SATTestController : Controller
    {
        private ApplicationUserManager userManager;
        private SATEntities db = new SATEntities();
        public ApplicationUserManager UserManager
        {
            get
            {
                return this.userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }

            private set
            {
                this.userManager = value;
            }
        }

        // GET: SATTest
        public ActionResult Index()
        {

            try
            {
                var categories = db.Categories.Where(t => t.ParentId == 1).OrderBy(t => t.OrderNumber).ToList();
                ViewBag.Categories = categories;
                ViewBag.Facebook = db.Settings.FirstOrDefault(t => t.Id == 2).Value;
                ViewBag.Youtube = db.Settings.FirstOrDefault(t => t.Id == 3).Value;
                ViewBag.Linked = db.Settings.FirstOrDefault(t => t.Id == 6).Value;
                ViewBag.Gplus = db.Settings.FirstOrDefault(t => t.Id == 5).Value;
                ViewBag.Instagram = db.Settings.FirstOrDefault(t => t.Id == 4).Value;

                ViewBag.Hotline = db.Settings.FirstOrDefault(t => t.Id == 1).Value;
                ViewBag.Address = db.Settings.FirstOrDefault(t => t.Key == "address").Value;
                ViewBag.Phone = db.Settings.FirstOrDefault(t => t.Key.Equals("phone")).Value;

                var email = Session["AccountEmail"].ToString();
                //var _user = await UserManager.FindByEmailAsync(email);
                using (var db = new SATEntities())
                {
                    var user = db.Users.Where(u => u.Email == email).OrderByDescending(u => u.Id).FirstOrDefault();
                    var userTestListInfo = db.SATTests.Include("SATTestSections").Where(u => u.UserID == user.Id).ToList();

                    return View(userTestListInfo);
                }
            }
            catch (Exception)
            {

                return RedirectToRoute("SATLogin");
            }
        }

        public ActionResult Test()
        {

            try
            {
                using (var db = new SATEntities())
                {
                    var email = Session["AccountEmail"].ToString();
                    var user = db.Users.Where(u => u.Email == email).FirstOrDefault();
                    var countTest = db.SATTests.Where(t => t.UserID == user.Id);
                    if (countTest != null && countTest.ToList().Count > 0)
                    {
                        var examForm = db.SATExamForms.OrderBy(e => e.Section).Where(e => e.Status == true).ToList();
                        ViewBag.ExamForm = examForm;
                        return View();
                    }
                    return RedirectToRoute("SATTestIndex");

                }
            }
            catch (Exception)
            {

                return RedirectToRoute("SATLogin");
            }

        }

        [HttpPost]
        public ActionResult Test(SATTest model, FormCollection collection)
        {

            var choose = collection.Get("sectionValue");
            var examCode = !string.IsNullOrEmpty(collection.Get("examCode")) ? int.Parse(collection.Get("examCode")) : 1;
            using (var db = new SATEntities())
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        var email = Session["AccountEmail"].ToString();
                        var user = db.Users.Where(u => u.Email == email).FirstOrDefault();
                        var now = DateTime.Now;
                        var section = int.Parse(choose);

                        var _existTest = db.SATTests.Include("User").Any(u => u.UserID == user.Id && (u.User.IsDeleted == null || u.User.IsDeleted == false) && u.ExamCode == examCode);
                        if (_existTest)
                        {
                            var testData = db.SATTests.FirstOrDefault(t => t.UserID == user.Id && t.Status == false);

                            var sectionData = testData.SATTestSections.FirstOrDefault(s => s.Section == section);
                            sectionData.TotalRightAnswer = 0;
                            //var type = db.SATExamForms.Where(e => e.TypeID == section).FirstOrDefault();
                            //var typeID = type != null ? type.TypeID : 0;
                            var defaultScore = db.SATScores.Where(s => s.RawValue == 0 && s.TypeID == section).FirstOrDefault();
                            sectionData.ScoreID = defaultScore.ID;
                            sectionData.Section = section;
                            sectionData.rowguid = testData.rowguid;
                            sectionData.StartTime = now;
                            sectionData.EndTime = now.AddMinutes(Utils.Instance.GetSectionDuration(section));

                            var entry = db.Entry(sectionData);
                            entry.State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                            Session["Section"] = section;
                            TempData["guidTest"] = testData.rowguid.ToString();
                            TempData.Keep("guidTest");
                            transaction.Commit();
                            return RedirectToAction("BeginTest", new { guid = testData.rowguid });
                        }
                        else
                        {
                            //new test
                            #region NewTest
                            var duration = Utils.Instance.GetSectionDuration(section);
                            // add pre define test
                            var beginTest = new SATTest();
                            beginTest.ExamCode = examCode;
                            beginTest.StartTime = now;
                            beginTest.EndTime = now.AddMinutes(duration);
                            beginTest.SubmitTime = beginTest.EndTime;
                            beginTest.TotalScore = 0;
                            beginTest.Status = false;// true is done the test
                            beginTest.rowguid = Guid.NewGuid();
                            beginTest.UserID = user.Id;

                            db.SATTests.Add(beginTest);
                            db.SaveChanges();

                            var currentTest = db.SATTests.Where(t => t.rowguid == beginTest.rowguid).FirstOrDefault();

                            var timeStep = now;
                            var testSectionRedirectGuid = Guid.Empty;

                            //add pre define section
                            for (int i = 1; i < 5; i++)
                            {
                                var testSection = new SATTestSection();
                                testSection.TestID = currentTest.ID;
                                testSection.TotalRightAnswer = 0;
                                //var type = db.SATExamForms.Where(e => e.Section == i).FirstOrDefault().TypeID;
                                var type = i;
                                var defaultScore = db.SATScores.Where(s => s.RawValue == 0 && s.TypeID == type).FirstOrDefault();
                                testSection.ScoreID = defaultScore.ID;
                                testSection.Section = i;
                                testSection.rowguid = beginTest.rowguid;
                                switch (i)
                                {
                                    case 1:
                                        testSection.StartTime = now;
                                        testSection.EndTime = now.AddMinutes(65);
                                        timeStep = testSection.EndTime;


                                        break;
                                    case 2:
                                        testSection.StartTime = timeStep;
                                        testSection.EndTime = timeStep.AddMinutes(35);
                                        timeStep = testSection.EndTime;
                                        break;
                                    case 3:
                                        testSection.StartTime = timeStep;
                                        testSection.EndTime = timeStep.AddMinutes(25);
                                        timeStep = testSection.EndTime;
                                        break;
                                    case 4:
                                        testSection.StartTime = timeStep;
                                        testSection.EndTime = timeStep.AddMinutes(55);
                                        timeStep = testSection.EndTime;
                                        break;
                                    default:
                                        break;
                                }
                                testSection.Status = false;
                                db.SATTestSections.Add(testSection);
                                db.SaveChanges();
                            }
                            Session["Section"] = section;
                            ////add pre define user answer
                            //foreach (var item in db.SATQuestions.ToList())
                            //{
                            //    var userAnswer = new SATUserAnswer();

                            //    userAnswer.rowguid = Guid.NewGuid();

IEE.Web/Views/SATTest/Test.cshtml
@model IEE.Infrastructure.DbContext.SATTest
@using IEE.Infrastructure.DbContext
@{
    ViewBag.Title = "Choose Section";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var form = (List<SATExamForm>)ViewBag.ExamForm;
}
@*@using (Html.BeginForm("Test","SATTest"))
    {


    <div>
        @Html.RadioButtonFor(model=>model.ExamCode,1,new {@checked="checked" }) 1
        @Html.RadioButtonFor(model => model.ExamCode, 2) 2
        <input type="submit" class="btn-success" value="Submit" />
    </div>
    }
    <table class="table">
        <tr>
    @foreach (var item in form)
    {
        <th>
            @Html.DisplayFor(model => item.Title)
        </th>
    }

        </tr>


        <tr>@foreach (var item in form)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Direction)
            </td>
        }
        </tr>


    </table>*@
<header style="margin-top:20px">
    <section class="container-fluid" style="padding:0; z-index:9">
        <!-- logo + menu -->
        <div id="headerQuiz">
            <div class="col-md-1"></div>
            <div class="col-md-2 headerTitleQuiz">
                <h3></h3>
            </div>
            <div class="col-md-5"></div>
            <div class="col-md-5 headerTitleQuiz">
                <h3>Entrance test</h3>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-2 headerButtonQuiz">
                <h3></h3>
            </div>
            <div class="col-md-1"></div>
        </div>
        <!-- end logo + menu -->
    </section>
</header>
<article>
    <div class="container-fluid contentQuiz" style="padding:0 8.3%">
        <div class="row quizGuide" style="padding:2%">
            <div class="col-md-1"></div>
            @using (Html.BeginForm("Test", "SATTest", FormMethod.Post))
            {
                <input type="hidden" name="sectionValue" id="sectionValue" />
                <input type="hidden" name="examCode" id="examCode" />
                <div class="col-md-10">
                    <h3>Hướng dẫn</h3>
                    <ul class="nav nav-pill" style="margin-bottom:20px;">

                        <li class="col-sm-6 first active" style="text-align:center"><a href="" data-toggle="tab" onclick="chooseExam(1);"><span><b> Đề 1</b></span></a><input style="display:none" type="radio" name=" chooseExam" value="1" id="" /></li>

                        <li class="col-sm-6 two" style="text-align:center"><a href="" data-toggle="tab" onclick="chooseExam(2);"><span><b>Đề 2</b></span></a><input style="display:none" type="radio" name="chooseExam" value="2" id="" /></li>

                    </ul>
                    <div id="sectionContainer">
                        <ul class="nav nav-pill">
                            @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(1))
                            {
                                <li class="col-sm-3 first active"><a href="#1b" data-toggle="tab" onclick="chooseSection(1);"><span><b> 1 - Reading</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="1" id="readingTab" /></li>
                            }
                            @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(2))
                            {
                                <li class="col-sm-3 two"><a href="#2b" data-toggle="tab" onclick="chooseSection(2);"><span><b> 2 - Writing & Language</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="2" id="writingTab" /></li>}
                            @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(3))
                            {
                                <li class="col-sm-3 two three"><a href="#3b" data-toggle="tab" onclick="chooseSection(3);"><span><b> 3 - Math No Calculator</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="3" id="math1Tab" /></li>}
                            @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(4))
                            {
                                <li class="col-sm-3 last"><a href="#4b" data-toggle="tab" onclick="chooseSection(4);"><span><b> 4 - Math Calculator</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="4" id="math2Tab" /></li>}
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="1b">
                                <h3>Reading</h3>
                                <p>
                                    Kỹ năng Reading được thực hiện trong vòng 65 phút, 52 câu hỏi.<br />
                                    Chuyển đến phần Section 1 của phiếu trả lời để trả lời câu hỏi của phần này. <br />
                                </p>
                                Mỗi đoạn văn/ mỗi cặp đoạn văn dưới đây đi kèm với một số câu hỏi. Sau khi đọc xong đoạn văn/ cặp đoạn văn, hãy chọn câu trả lời dựa trên những ý kiến được biểu đạt tường minh hay hàm ẩn trong đoạn văn và trong các biểu đồ (ví dụ như biểu đồ cột hay biểu đồ đường).

                                @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(1))
                                {
                                    <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

                                }

                                <div class="clear"></div>
                            </div>
                            <div class="tab-pane" id="2b">
                                <h3>Writing & Language</h3>
                                <p>Kỹ năng Writing được thực hiện trong vòng 35 phút, 44 câu hỏi. Chuyển đến phần Section 2 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
                                <p>Hướng dẫn:</p>
                                -	Mỗi đoạn văn đều có kèm theo các câu hỏi. Một số câu hỏi sẽ hỏi bạn xem tác giả nên viết lại và tăng cường tính biểu đạt của đoạn văn như thế nào. Một số câu hỏi sẽ yêu cầu bạn sửa lỗi trong câu trúc câu, cách sử dụng hay dấu câu. Sẽ có những câu hỏi yêu cầu bạn phải xem kĩ một biểu đồ khi bạn viết lại hay sửa đoạn văn.<br />
                                -	Một số câu hỏi sẽ liên quan đến một phần của đoạn văn được gạch chân. Một số câu hỏi sẽ liên quan đến những chi tiết trong đoạn văn hoặc yêu cầu bạn phải đọc toàn bộ đoạn văn.<br />
                                -	Sau khi bạn đọc đoạn văn, hãy chọn câu trả lời giúp cải thiện đoạn văn hiệu quả nhất hay giúp đoạn văn tuân theo quy chuẩn văn viết tiếng Anh. Rất nhiều câu hỏi có lựa chọn “NO CHANGE”. Hãy chọn câu trả lời “NO CHANGE” khi bạn thấy rằng các phần còn lại của đoạn văn nên được giữ nguyên.<br />

                                @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(2))
                                {
                                    <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

                                }
                                <div class="clear"></div>
                            </div>
                            <div class="tab-pane" id="3b">
                                <h3>Math No Calculator</h3>
                                <p>Kỹ năng Math No Calculator được thực hiện trong vòng 25 phút, 20 câu hỏi. Chuyển đến phần Section 3 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
                                <p>Hướng dẫn:</p>
                                Câu hỏi số 1 – 15 yêu cầu bạn phải tìm ra câu trả lời đúng cho câu hỏi bằng cách chọn lựa một trong bốn đáp án được đưa ra và tô kín hình tròn tương ứng với đáp án trong phiếu trả lời. Câu hỏi 16-20 yêu cầu bạn trả lời câu hỏi và điền đáp án của bạn vào ô cho sẵn trong phiếu trả lời. Sẽ có các hướng dẫn chi tiết về cách điền câu trả lời vào ô cho sẵn trước câu hỏi số 16. Bạn có thể sử dụng quyển đề bài để ghi nháp.
                                <p>Ghi chú:</p>
                                1.	Bạn không được sử dụng máy tính bỏ túi.<br />
                                2.	Các biến số và kí hiệu là biểu hiện cho số thực (nếu không có ghi chú đặc biệt nào khác).<br />
                                3.	Hình vẽ được vẽ theo tỉ lệ (nếu không có ghi chú đặc biệt nào khác).<br />
                                4.	Hình vẽ nằm trên mặt phẳng (nếu không có ghi chú đặc biệt nào khác).<br />
                                5.	Tập xác định của hàm số f(x) là tập số thực (nếu không có ghi chú đặc biệt nào khác).<br />
                                <img src="~/Content/img/step3.png" />
                                @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(3))
                                {
                                    <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

                                }
                                <div class="clear"></div>
                            </div>
                            <div class="tab-pane" id="4b">
                                <h3>Math Calculator</h3>
                                <p>Kỹ năng Math Calculator được thực hiện trong vòng 55 phút, 38 câu hỏi. Chuyển đến phần Section 4 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
                                -	Câu hỏi số 1 – 30 yêu cầu bạn phải tìm ra câu trả lời đúng cho câu hỏi bằng cách chọn lựa một trong bốn đáp án được đưa ra và tô kín hình tròn tương ứng với đáp án trong phiếu trả lời. Câu hỏi 31 - 38 yêu cầu bạn trả lời câu hỏi và điền đáp án của bạn vào ô cho sẵn trong phiếu trả lời. Sẽ có các hướng dẫn chi tiết về cách điền câu trả lời vào ô cho sẵn trước câu hỏi số 16. Bạn có thể sử dụng quyển đề bài để ghi nháp.
                                <p>Ghi chú:</p>
                                1.	Bạn không được sử dụng máy tính bỏ túi.<br />
                                2.	Các biến số và kí hiệu là biểu hiện cho số thực (nếu không có ghi chú đặc biệt nào khác).<br />
                                3.	Hình vẽ được vẽ theo tỉ lệ (nếu không có ghi chú đặc biệt nào khác).<br />
                                4.	Hình vẽ nằm trên mặt phẳng (nếu không có ghi chú đặc biệt nào khác).<br />
                                5.	Tập xác định của hàm số f(x) là tập số thực (nếu không có ghi chú đặc biệt nào khác).<br />
                                <img src="~/Content/img/step4.png" />
                                @if (Session["DisabledSection"] == null || !((List<int>)Session["DisabledSection"]).Contains(4))
                                {
                                    <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

                                }
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-1"></div>
        </div>
    </div>
</article>
@if (ViewBag.Ex!=null)
{
    @ViewBag.Ex
}
<script>
    $(document).ready(function () {
        chooseSection(1);
        chooseExam(1);

    });
    function chooseSection(sectionId) {
        //$('' + sectionId + '').prop("checked", true);
        $('#sectionValue').val(sectionId);
    }

    function chooseExam(sectionId) {
        $.get('/sattest/GetAllSection?examCode=' + sectionId, function (data) {
            $('#sectionContainer').html(data);
        });
        //$('' + sectionId + '').prop("checked", true);
        $('#examCode').val(sectionId);
    }
</script>

IEE.Web/Views/SATTest/_ChooseSection.cshtml
@model IEE.Web.Models.DisabledSection

<ul class="nav nav-pill">
    @if (Model.Section == null || !Model.Section.Contains(1))
    {
        <li class="col-sm-3 first active"><a href="#1b" data-toggle="tab" onclick="chooseSection(1);"><span><b> 1 - Reading</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="1" id="readingTab" /></li>
    }
    else
    {
        <li class="col-sm-3 first active"><a><span><b style="color:#d0d0d0"> 1 - Reading</b></span></a></li>

    }

    @if (Model.Section == null || !Model.Section.Contains(2))
    {
        <li class="col-sm-3 two"><a href="#2b" data-toggle="tab" onclick="chooseSection(2);"><span><b> 2 - Writing & Language</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="2" id="writingTab" /></li>
    }
    else
    {
        <li class="col-sm-3 two"><a><span><b style="color:#d0d0d0"> 2 - Writing & Language</b></span></a></li>
    }
    @if (Model.Section == null || !Model.Section.Contains(3))
    {
        <li class="col-sm-3 two three"><a href="#3b" data-toggle="tab" onclick="chooseSection(3);"><span><b> 3 - Math No Calculator</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="3" id="math1Tab" /></li>
    }
    else
    {
        <li class="col-sm-3 two three"><a><span><b style="color:#d0d0d0"> 3 - Math No Calculator</b></span></a></li>

    }
    @if (Model.Section == null || !Model.Section.Contains(4))
    {
        <li class="col-sm-3 last"><a href="#4b" data-toggle="tab" onclick="chooseSection(4);"><span><b> 4 - Math Calculator</b></span></a><input style="display:none" type="radio" name=" chooseSection" value="4" id="math2Tab" /></li>
    }
    else
    {
        <li class="col-sm-3 last"><a><span><b style="color:#d0d0d0"> 4 - Math Calculator</b></span></a></li>
    }
</ul>
<div class="tab-content">
    <div class="tab-pane active" id="1b">
        <h3>Reading</h3>
        <p>
            Kỹ năng Reading được thực hiện trong vòng 65 phút, 52 câu hỏi.<br />
            Chuyển đến phần Section 1 của phiếu trả lời để trả lời câu hỏi của phần này. <br />
        </p>
        Mỗi đoạn văn/ mỗi cặp đoạn văn dưới đây đi kèm với một số câu hỏi. Sau khi đọc xong đoạn văn/ cặp đoạn văn, hãy chọn câu trả lời dựa trên những ý kiến được biểu đạt tường minh hay hàm ẩn trong đoạn văn và trong các biểu đồ (ví dụ như biểu đồ cột hay biểu đồ đường).

        @if (Model.Section == null || !Model.Section.Contains(1))
        {
            <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

        }

        <div class="clear"></div>
    </div>
    <div class="tab-pane" id="2b">
        <h3>Writing & Language</h3>
        <p>Kỹ năng Writing được thực hiện trong vòng 35 phút, 44 câu hỏi. Chuyển đến phần Section 2 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
        <p>Hướng dẫn:</p>
        -	Mỗi đoạn văn đều có kèm theo các câu hỏi. Một số câu hỏi sẽ hỏi bạn xem tác giả nên viết lại và tăng cường tính biểu đạt của đoạn văn như thế nào. Một số câu hỏi sẽ yêu cầu bạn sửa lỗi trong câu trúc câu, cách sử dụng hay dấu câu. Sẽ có những câu hỏi yêu cầu bạn phải xem kĩ một biểu đồ khi bạn viết lại hay sửa đoạn văn.<br />
        -	Một số câu hỏi sẽ liên quan đến một phần của đoạn văn được gạch chân. Một số câu hỏi sẽ liên quan đến những chi tiết trong đoạn văn hoặc yêu cầu bạn phải đọc toàn bộ đoạn văn.<br />
        -	Sau khi bạn đọc đoạn văn, hãy chọn câu trả lời giúp cải thiện đoạn văn hiệu quả nhất hay giúp đoạn văn tuân theo quy chuẩn văn viết tiếng Anh. Rất nhiều câu hỏi có lựa chọn “NO CHANGE”. Hãy chọn câu trả lời “NO CHANGE” khi bạn thấy rằng các phần còn lại của đoạn văn nên được giữ nguyên.<br />

        @if (Model.Section == null || !Model.Section.Contains(2))
        {
            <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

        }
        <div class="clear"></div>
    </div>
    <div class="tab-pane" id="3b">
        <h3>Math No Calculator</h3>
        <p>Kỹ năng Math No Calculator được thực hiện trong vòng 25 phút, 20 câu hỏi. Chuyển đến phần Section 3 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
        <p>Hướng dẫn:</p>
        Câu hỏi số 1 – 15 yêu cầu bạn phải tìm ra câu trả lời đúng cho câu hỏi bằng cách chọn lựa một trong bốn đáp án được đưa ra và tô kín hình tròn tương ứng với đáp án trong phiếu trả lời. Câu hỏi 16-20 yêu cầu bạn trả lời câu hỏi và điền đáp án của bạn vào ô cho sẵn trong phiếu trả lời. Sẽ có các hướng dẫn chi tiết về cách điền câu trả lời vào ô cho sẵn trước câu hỏi số 16. Bạn có thể sử dụng quyển đề bài để ghi nháp.
        <p>Ghi chú:</p>
        1.	Bạn không được sử dụng máy tính bỏ túi.<br />
        2.	Các biến số và kí hiệu là biểu hiện cho số thực (nếu không có ghi chú đặc biệt nào khác).<br />
        3.	Hình vẽ được vẽ theo tỉ lệ (nếu không có ghi chú đặc biệt nào khác).<br />
        4.	Hình vẽ nằm trên mặt phẳng (nếu không có ghi chú đặc biệt nào khác).<br />
        5.	Tập xác định của hàm số f(x) là tập số thực (nếu không có ghi chú đặc biệt nào khác).<br />
        <img src="~/Content/img/step3.png" />
        @if (Model.Section == null || !Model.Section.Contains(3))
        {
            <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

        }
        <div class="clear"></div>
    </div>
    <div class="tab-pane" id="4b">
        <h3>Math Calculator</h3>
        <p>Kỹ năng Math Calculator được thực hiện trong vòng 55 phút, 38 câu hỏi. Chuyển đến phần Section 4 của phiếu trả lời để trả lời câu hỏi của phần này. </p>
        -	Câu hỏi số 1 – 30 yêu cầu bạn phải tìm ra câu trả lời đúng cho câu hỏi bằng cách chọn lựa một trong bốn đáp án được đưa ra và tô kín hình tròn tương ứng với đáp án trong phiếu trả lời. Câu hỏi 31 - 38 yêu cầu bạn trả lời câu hỏi và điền đáp án của bạn vào ô cho sẵn trong phiếu trả lời. Sẽ có các hướng dẫn chi tiết về cách điền câu trả lời vào ô cho sẵn trước câu hỏi số 16. Bạn có thể sử dụng quyển đề bài để ghi nháp.
        <p>Ghi chú:</p>
        1.	Bạn không được sử dụng máy tính bỏ túi.<br />
        2.	Các biến số và kí hiệu là biểu hiện cho số thực (nếu không có ghi chú đặc biệt nào khác).<br />
        3.	Hình vẽ được vẽ theo tỉ lệ (nếu không có ghi chú đặc biệt nào khác).<br />
        4.	Hình vẽ nằm trên mặt phẳng (nếu không có ghi chú đặc biệt nào khác).<br />
        5.	Tập xác định của hàm số f(x) là tập số thực (nếu không có ghi chú đặc biệt nào khác).<br />
        <img src="~/Content/img/step4.png" />
        @if (Model.Section == null || !Model.Section.Contains(4))
        {
            <button type="submit" href="@Url.RouteUrl("SATTest")" class="quizButton" style="border:none;">Start</button>

        }
        <div class="clear"></div>
    </div>
</div>