IEE.Web/Controllers/CmsBaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using IEE.ViewModel;
using System.Web.Mvc;
using IEE.Infrastructure.DbContext;

using AutoMapper;
using System.Configuration;
using System.Web;
using IEE.Web.Business;
using System.Net.Mail;
using System.Text;
using System.Net;
using System.Text.RegularExpressions;
using IEE.Infrastructure;

namespace IEE.Web.Controllers
{
    public class CmsBaseController : Controller
    {
        private readonly IRepository<Category> _categoryRepo;
        private readonly IRepository<Consultant> _consultRepo;
        private readonly IRepository<Program> _proRepo;
        private readonly IRepository<Post> _postRepo;
        private readonly IRepository<Setting> _settingRepo;
        private readonly IRepository<StudentHighlight> _studentRepo;
        private readonly IRepository<TeacherHighlight> _teacherRepo;
        private readonly IRepository<UniversityHighlight> _universityRepo;
        private readonly IRepository<Banner> _bannerRepo;
        public CmsBaseController()
        {
            UnitOfWork dbContext = new UnitOfWork();


            _categoryRepo = dbContext.GetRepository<Category>();
            _settingRepo = dbContext.GetRepository<Setting>();
            _postRepo = dbContext.GetRepository<Post>();
            _bannerRepo = dbContext.GetRepository<Banner>();


            _consultRepo = dbContext.GetRepository<Consultant>();
            _proRepo = dbContext.GetRepository<Program>();
            _universityRepo = dbContext.GetRepository<UniversityHighlight>();


            _studentRepo = dbContext.GetRepository<StudentHighlight>();
            _teacherRepo = dbContext.GetRepository<TeacherHighlight>();


        }

        public ActionResult Header()
        {

            var hotline = _settingRepo.Get(t => t.Id == 1);
            ViewBag.Hotline = hotline;

            ViewBag.Facebook = _settingRepo.Get(t => t.Id == 2).Value;
            ViewBag.Youtube = _settingRepo.Get(t => t.Id == 3).Value;
            ViewBag.Linked = _settingRepo.Get(t => t.Id == 6).Value;
            ViewBag.Gplus = _settingRepo.Get(t => t.Id == 5).Value;
            ViewBag.Instagram = _settingRepo.Get(t => t.Id == 4).Value;

            var categories = _categoryRepo.GetMany(t => t.IsDeleted == false && t.IsMenu == true && t.ParentId == 1).OrderBy(t => t.OrderNumber);
            return PartialView("_Header", categories);
        }
        public ActionResult Footer()
        {
            var hotline = _settingRepo.Get(t => t.Id == 1);
            ViewBag.Hotline = hotline;

            var categories = _categoryRepo.GetMany(t => t.IsDeleted == false && t.IsMenu == true);
            ViewBag.Categories = categories;

            ViewBag.Facebook = _settingRepo.Get(t => t.Id == 2).Value;
            ViewBag.Youtube = _settingRepo.Get(t => t.Id == 3).Value;
            ViewBag.Linked = _settingRepo.Get(t => t.Id == 6).Value;
            ViewBag.Gplus = _settingRepo.Get(t => t.Id == 5).Value;
            ViewBag.Instagram = _settingRepo.Get(t => t.Id == 4).Value;

            ViewBag.Hotline = _settingRepo.Get(t => t.Id == 1).Value;
            ViewBag.Phone = _settingRepo.Get(t => t.Id == 8).Value;
            ViewBag.Address = _settingRepo.Get(t => t.Id == 7).Value;

            return PartialView("_Footer");
        }
        public ActionResult ConsultRegister()
        {
            var programs = _proRepo.GetMany(t => t.IsDeleted == false);
            ViewBag.Programs = programs;
            return PartialView("_ConsultRegister");
        }

        [HttpPost]
        public ActionResult ConsultRegister(ConsultantViewModel model)
        {
            if (string.IsNullOrEmpty(model.Name) || string.IsNullOrEmpty(model.Email))
            {
                return Json(false);
            }
            else if (!this.IsValidEmail(model.Email))
            {
                return Json(false);
            }
            else
            {
                var consult = Mapper.Map<ConsultantViewModel, Consultant>(model);
                consult.CreatedDate = DateTime.Now;
                consult.IsDeleted = false;
                _consultRepo.InsertAndSubmit(consult);

                using (MailMessage mailMessage = new MailMessage())
                {
                    StringBuilder content = new StringBuilder();
                    content.Append("IEE nhận được yêu cầu tư vấn với các thông tin.");
                    content.AppendLine();
                    content.Append("Họ và tên: " + model.Name);
                    content.AppendLine();
                    content.Append("Địa chỉ: " + model.School);
                    content.AppendLine();
                    content.Append("Lớp: " + model.Class);
                    content.AppendLine();
                    content.Append("Điện thoại: " + model.Phone);
                    content.AppendLine();
                    content.Append("Email: " + model.Email);
                    content.AppendLine();
                    if (model.Program.HasValue)
                    {
                        string programName = _proRepo.Get(t => t.Id == model.Program.Value).Name;
                        content.Append("Chương trình mong muốn: " + programName);
                        content.AppendLine();
                    }
                    content.Append("Nội dung:");
                    content.AppendLine();
                    content.Append(model.Message);

                    mailMessage.From = new MailAddress(ConfigurationManager.AppSettings["UserName"]);
                    mailMessage.Subject = "IEE nhận được yêu cầu tư vấn với các thông tin";
                    mailMessage.Body = content.ToString();
                    mailMessage.IsBodyHtml = true;

                    mailMessage.To.Add(ConfigurationManager.AppSettings["Email"]);

                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = ConfigurationManager.AppSettings["Host"];
                    smtp.UseDefaultCredentials = false;
                    smtp.EnableSsl = true;
                    smtp.Port = int.Parse(ConfigurationManager.AppSettings["Port"]);

                    NetworkCredential NetworkCred = new System.Net.NetworkCredential();

                    NetworkCred.UserName = ConfigurationManager.AppSettings["UserName"];
                    NetworkCred.Password = ConfigurationManager.AppSettings["Password"];
                    smtp.Credentials = NetworkCred;
                    smtp.Send(mailMessage);

                }

                return Json(true);
            }
        }

        public ActionResult University()
        {
            var universities = _universityRepo.GetMany(t => t.IsDeleted == false);
            return PartialView("_University", universities);
        }
        public ActionResult Student()
        {
            var students = _studentRepo.GetMany(t => t.IsDeleted == false);
            return PartialView("_Student", students);
        }
        public ActionResult Teacher()
        {
            var teachers = _teacherRepo.GetMany(t => t.IsDeleted == false).OrderBy(o => o.DisplayIndex).ToList();
            return PartialView("_Teacher", teachers);
        }
        public ActionResult LeftPostRandom()
        {
            Random rnd = new Random();
            var posts = _postRepo.GetMany(t => t.IsDeleted == false && t.PostCategories.Select(c => c.Category).Any(c => c.Controller.Equals("news")) == true).OrderByDescending(t => rnd.Next()).Take(5);
            var student = _studentRepo.GetMany(t => t.IsDeleted == false).OrderByDescending(t => rnd.Next()).Take(1).FirstOrDefault();
            ViewBag.Student = student;

            var sat = _settingRepo.Get(t => t.Id == 11);
            ViewBag.Sat = sat;

            var toefl = _settingRepo.Get(t => t.Id == 13);
            ViewBag.Toefl = toefl;

            var ielfs = _settingRepo.Get(t => t.Id == 15);
            ViewBag.Ielfs = ielfs;

            var sat_new = _settingRepo.Get(t => t.Id == 11);
            ViewBag.SatNew = sat_new;

            var toefl_new = _settingRepo.Get(t => t.Id == 13);
            ViewBag.ToeflNew = toefl_new;

            var ielfs_new = _settingRepo.Get(t => t.Id == 15);
            ViewBag.IelfsNew = ielfs_new;

            return PartialView("_LeftPostRandom", posts);
        }
        public ActionResult LeftPostProgramRandom(int category)
        {
            Random rnd = new Random();
            var posts = _postRepo.GetMany(t => t.IsDeleted == false && t.PostCategories.Select(c => c.Category).Any(c => c.Controller.Equals("news")) == true).OrderByDescending(t => rnd.Next()).Take(2);
            var student = _studentRepo.GetMany(t => t.IsDeleted == false).OrderByDescending(t => rnd.Next()).Take(1).FirstOrDefault();
            ViewBag.Student = student;

            var sat = _settingRepo.Get(t => t.Id == 11);
            ViewBag.Sat = sat;

            var toefl = _settingRepo.Get(t => t.Id == 13);
            ViewBag.Toefl = toefl;

            var ielfs = _settingRepo.Get(t => t.Id == 15);
            ViewBag.Ielfs = ielfs;

            var sat_new = _settingRepo.Get(t => t.Id == 11);
            ViewBag.SatNew = sat_new;

            var toefl_new = _settingRepo.Get(t => t.Id == 13);
            ViewBag.ToeflNew = toefl_new;

            var ielfs_new = _settingRepo.Get(t => t.Id == 15);
            ViewBag.IelfsNew = ielfs_new;

            var categoryObj = _categoryRepo.Get(t => t.Id == category);
            ViewBag.Categories = _categoryRepo.GetMany(c => c.ParentId == categoryObj.Id).OrderBy(t => t.OrderNumber).OrderBy(t => t.Name);

            return PartialView("_LeftPostProgramRandom", posts);
        }
        public ActionResult LeftAbout()
        {
            Random rnd = new Random();
            var student = _studentRepo.GetMany(t => t.IsDeleted == false).OrderByDescending(t => rnd.Next()).Take(1).FirstOrDefault();
            ViewBag.Student = student;

IEE.Web/Views/News/Category.cshtml
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using IEE.Web.Models;
@using IEE.Web.Areas.ttn_content.Models;
@model IEE.Infrastructure.DbContext.Category
@{
    if (Model == null)
    {
        return;
    }
    var partialViewModel = new PartialViewModel();
    partialViewModel.Cate = Model;

   
}
@if (Model.PostCategories != null && Model.PostCategories.Select(p => p.Post).Where(p => p != null).Count() > 0)
{
    var skip = (int)ViewBag.PageCount * (int)ViewBag.Trang;
    var _pageCount = (int)ViewBag.PageCount;
    var _trang = (int)ViewBag.Trang;
    var postModel = Model.PostCategories.Select(p => p.Post).Where(p => p != null).ToList().OrderByDescending(p => p.PublishedDate).Skip((_trang-1)*_pageCount).Take(_pageCount).ToList();
    partialViewModel.ListPost = postModel;
}
<article>
    <div class="container-fluid" style="padding:0 8.3%">
        <div class="row" style="padding:2%">
            <div class="col-md-9" style="padding-right:2%; padding-left:0;">
                <div id="main-left" style="padding:2%">
                    @*<div id="navigation-bar">
                        <div style="padding:0 0 0 1.5%">
                            <a href="#"><p>Trang chủ</p></a>
                            <p>--</p>
                            <a href="#"><p class="active">Tin tức</p></a>
                            <p>--</p>
                            <a href="#"><p class="active">@Model.Name</p></a>
                        </div>
                        <div style="clear:both"></div>
                        <hr>
                    </div>*@
                  
                    @MvcHtmlString.Create(Utils.Instance.ReturnPartialContent(partialViewModel))
                    <div style="clear:both"></div>
                </div>
               

                <div class="paging">
                    <ul>
                        @if (ViewBag.TotalPage != null && ViewBag.TotalPage > 1)
                        {
                            <li><a href="@Url.RouteUrl("CatSEORoute",new {Category= ViewBag.Cat,trang=1 })"> << </a></li>
                            for (int i = 1; i < ViewBag.TotalPage + 1; i++)
                            {

                                <li> <a href="@Url.RouteUrl("CatSEORoute",new {Category= ViewBag.Cat,trang=i })">@i </a></li>

                            }
                            <li><a href="@Url.RouteUrl("CatSEORoute",new {Category= ViewBag.Cat,trang=(int)ViewBag.TotalPage })"> >> </a></li>
                        }
                    </ul>
                </div>
                <!-- end main-left -->
            </div>
            <div class="col-md-3" id="main-right">
            @Html.Partial("_RightPart", ViewBag.Banners as List<IEE.Infrastructure.DbContext.Banner>)
                </div>
        </div>
    </div>
</article>

IEE.Web/Views/News/Content.cshtml
@using IEE.Infrastructure.DbContext

@model IEE.Infrastructure.DbContext.Post
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.Title;

    ViewBag.MetaKeys = Model.MetaKey != null ? Model.MetaKey : "";
    ViewBag.MetaDescription = !string.IsNullOrEmpty(Model.MetaDescription) ? Model.MetaDescription : "Đơn vị luyện thi SAT, IELTS, TOEFL ibt & tư vấn du học Mỹ hàng đầu";




    string domain = string.Empty, currentUrl = string.Empty, summarize = string.Empty, photo = string.Empty, title = string.Empty;
    Uri url = HttpContext.Current.Request.Url;
    domain = url.AbsoluteUri.Replace(url.PathAndQuery, string.Empty);

    title = Model.Title;
    currentUrl = domain + "/about/group/" + Model.Id;
    if (!string.IsNullOrEmpty(Model.Summarize))
    {
        summarize = Model.Summarize.Length <= 200 ? Model.Summarize : Model.Summarize.Substring(0, 200) + "...";
    }

    if (string.IsNullOrEmpty(Model.Photo))
    {
        photo = domain + "/photo/header-logo.png";
    }
    else
    {
        photo = domain + "/photo/post/" + Model.Photo;
    }
    string cat = ViewBag.category.ToString();
}
@section MetaTags
{
    <meta property="og:url" content="@url" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="@Model.Title" />
    <meta property="og:description" content="@summarize" />
    <meta property="og:image" content="@photo" />

}

<article>
    <div class="container-fluid" style="padding:0 8.3%">
        <div class="row" style="padding:2%">
            <div class="col-md-9" style="padding-right:2%; padding-left:0;">
                <div id="main-left">
                    <div id="navigation-bar">
                        <div style="padding:0 0 0 1.5%">
                            <a href="#"><p>Trang chủ</p></a>
                            <p>--</p>
                            <a href="@Url.RouteUrl("CatSEORoute", new { Category = cat.ToSeoUrl() })"><p>@cat</p></a>
                            <p>--</p>
                            <a href="@Url.RouteUrl("NewsSEORoute", new {category=cat.ToSeoUrl() , title = Model.Title.ToSeoUrl(), id = Model.Id })"><p class="active">@Model.Title</p></a>
                        </div>
                        <div style="clear:both"></div>
                        <hr>
                    </div>

                    <div id="main-left-content">
                        <div id="news">

                            <h1 id="news-title">@Model.Title</h1>
                            <p id="news-time">
                                @if (Model.PublishedDate.HasValue)
                                {
                                    @Model.PublishedDate.Value.ToString("dd-MM-yyyy")

                                }
                            </p>
                            <hr>
                            <p id="news-description">
                                @* @Model.Summarize*@
                            </p>

                            @MvcHtmlString.Create(Model.Detail)
                        </div>
                    </div>
                    <!-- end news -->
                    <hr>
                    <div id="related-articles">
                        <h2>Bài viết liên quan :</h2>
                        <ul>

                            @foreach (var item in (List<Post>)ViewBag.RelatePost)
                            {
                                <li><a href="@Url.RouteUrl("NewsSEORoute", new { title = item.Title.ToSeoUrl(), id = item.Id })">@item.Title</a></li>
                            }
                        </ul>
                    </div>
                    <!-- end related-articles -->
                </div>
                <!-- end main-left-content -->
                <div style="clear:both"></div>
            </div>
            <!-- end main-left -->
            <div class="col-md-3" id="main-right">
                @Html.Partial("_RightPart", ViewBag.Banners as List<IEE.Infrastructure.DbContext.Banner>)
            </div>
        </div>
    </div>
</article>

IEE.Web/Views/News/Index.cshtml
@{
    ViewBag.Title = "Tin tức";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<section id="page-news">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li>
                            <strong><a href="/">IEE</a></strong>
                        </li>
                        <li>
                            Tin tức
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12" id="news-list">
                @Html.Partial("_Articles", (ViewBag.Posts as Dictionary<int, IEE.Infrastructure.DbContext.Post>))
            </div>
        </div>
    </div>
   @Html.Partial("_Loading")
</section>*@

<article>
    <div class="container-fluid" style="padding:0 8.3%">
        <div class="row" style="padding:2%">
            <div class="col-md-9" style="padding-right:2%; padding-left:0;">
                <div id="main-left">
                    <div id="navigation-bar">
                        <div style="padding:0 0 0 1.5%">
                            <a href="#"><p>Trang chủ</p></a>
                            <p>--</p>
                            <a href="#"><p class="active">Tin tức</p></a>
                        </div>
                        <div style="clear:both"></div>
                        <hr>
                    </div>
                  
                    <!-- end main-left-content -->
                    <div style="clear:both"></div>
                </div>
                <!-- end main-left -->
            </div>
            <div class="col-md-3" id="main-right">
                <div id="confuse">
                    <p>Bạn muốn biết khả năng SAT của mình ?</p>
                    <a href="#"><p id="confuse-button">Test ngay >> </p></a>
                </div>
                <hr>
                <div id="introduce">
                    <p>Khóa học có thể phù hợp với bạn</p>
                    <a href="#"><p id="introduce-button">SAT Advance</p></a>
                </div>
                <hr>
                <div id="right-advetise">
                    <a href="#"><img src="images/adv2.png"></a>
                    <a href="#"><img src="images/adv1.png"></a>
                    <a href="#"><img src="images/adv3.png"></a>
                </div>
            </div>
        </div>
    </div>
</article>


@*@section scripts{
    <script src="~/scripts/infiniteScroll.js"></script>
    <script type="text/javascript">
        $(function () {
            $("div#loading").hide();
        });
        var moreRowsUrl = '@Url.Action("index", "news")';
        $(window).scroll(divScrollHandler);
    </script>
}*@

IEE.Web/Views/News/Preview.cshtml
@model IEE.Infrastructure.DbContext.Post
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Page.cshtml";
}
<section id="page-news">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-6">
                    <ol class="breadcrumb">
                        <li>
                            <strong><a href="/">IEE</a></strong>
                        </li>
                        <li>
                            Tin tức
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-8 ">
                    <div class="news-content p-md box-shadow">
                        @if (Model != null)
                        {
                        <h4 class="text-bold">@Model.Title</h4>
                        <h6 class="m-b-md">
                            <i>
                                @{
                                    string dayStr = string.Empty;
                                    var previewDate = Model.PublishedDate.HasValue ? Model.PublishedDate.Value : DateTime.Now;
                                    int day = (int)DateTime.Now.Subtract(previewDate).TotalDays;
                                }
                                @if (day != 0)
                                {
                                    dayStr = day + " ngày trước";
                                }
                                else
                                {
                                    dayStr = "Hôm nay";
                                }
                                @dayStr
                            </i>
                        </h6>
                        <div id="news-content-detail">
                            @Html.Raw(Model.Detail)
                        </div>

                                    }
                    </div>
                </div>
                @{Html.RenderAction("LeftPostRandom", "CmsBase");}
            </div>
        </div>
    </div>
</section>